## Numpy Tutorial

In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,4,5,1,8]] , np.int32)

In [3]:
myarr

array([[3, 4, 5, 1, 8]], dtype=int32)

In [4]:
myarr[0,1]

np.int32(4)

In [5]:
myarr.shape

(1, 5)

In [6]:
myarr.dtype


dtype('int32')

In [7]:
myarr[0,1]=33

In [8]:
myarr

array([[ 3, 33,  5,  1,  8]], dtype=int32)

### Array Creation : Conversion From other Python structure

In [9]:
np.array({3,2,6,})  #creates object type data

array({2, 3, 6}, dtype=object)

In [10]:
zero = np.zeros((2,5))

In [11]:
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
rng = np.arange(15)

In [13]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
lspace = np.linspace(1,8,40)


In [15]:
lspace

array([1.        , 1.17948718, 1.35897436, 1.53846154, 1.71794872,
       1.8974359 , 2.07692308, 2.25641026, 2.43589744, 2.61538462,
       2.79487179, 2.97435897, 3.15384615, 3.33333333, 3.51282051,
       3.69230769, 3.87179487, 4.05128205, 4.23076923, 4.41025641,
       4.58974359, 4.76923077, 4.94871795, 5.12820513, 5.30769231,
       5.48717949, 5.66666667, 5.84615385, 6.02564103, 6.20512821,
       6.38461538, 6.56410256, 6.74358974, 6.92307692, 7.1025641 ,
       7.28205128, 7.46153846, 7.64102564, 7.82051282, 8.        ])

In [16]:
emp = np.empty((2,3))

In [17]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [1.86921822e-306, 1.42413555e-306, 1.78019082e-306]])

In [18]:
ide = np.identity(7)

In [19]:
ide

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [20]:
arr = np.arange(99)

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [22]:
arr.reshape(11,9)  ;ravel for making 1D array

SyntaxError: invalid decimal literal (3120795765.py, line 1)

In [ ]:
x= [[1,2,3],[4,5,6,],[7,1,0,]]

In [ ]:
ar= np.array(x)

In [ ]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [ ]:
ar.sum(axis=0)

array([12,  8,  9])

In [ ]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [ ]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [ ]:
ar.flat

In [ ]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [ ]:
ar.ndim

2

In [ ]:
dd= ar*ar

In [ ]:
ar.sum()

np.int64(29)

In [ ]:
ar.sum

<function ndarray.sum>

In [ ]:
dd

array([[ 1,  4,  9],
       [16, 25, 36],
       [49,  1,  0]])